EMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('access.urls')),
    path('hrd/', include('employee.urls')),
    path('',include('leave.urls')),
    path('reservation/',include('booking.urls')),
    path("blog/", include('chat.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'SUDPAY ADMINISTRATION'

booking/urls.py
from django.urls import path

# from .views.main import index, ReservationCreate, ReservationUpdate
from .import views

urlpatterns = [
 
    path('booking', views.booking, name='book'),
]

booking/models.py
from django.db import models
from access.models import User
from datetime import datetime
from django.core.checks import register

# Create your models here.


class Room(models.Model):
    name = models.CharField(max_length=50)
    comment = models.TextField(
        blank=True,
        null=True,
        verbose_name=('comment'),
        help_text=('Describe what is special about this room, '
                    'such as available equipment.'),
    )

    def __str__(self):
        return self.name
    



class Booking(models.Model):
    
    room = models.ForeignKey(Room, verbose_name=("Meeting room"), on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name=("User"), on_delete=models.CASCADE)
    start_time = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True)
    end_time = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True)
    about = models.TextField(
            max_length=150,
            help_text=('See for example the meeting agenda.'),null=True, blank=True)
    is_validated = models.BooleanField(null=False,default=False) #hide

    class Meta:
        verbose_name = ("booking")
        verbose_name_plural = ("bookings")

    
    # def __str__(self):
    #     return str(self.start_time.hour) +"h"+ " a " + str(
    #         self.end_time.hour) +"h"+ " : " + self.room.name





    

booking/forms.py
from django import forms
from django.utils import timezone
from .models import Booking


class BookingForm(forms.ModelForm):
    
    class Meta:
        model = Booking
        exclude = ['user', 'is_validated']

    def clean(self):
        """
        Check global form constraints
        """
        cleaned_data = super().clean()
        is_validated = cleaned_data.get('is_validated')
        start_time = cleaned_data.get('start_time')
        end_time = cleaned_data.get('end_time')

        # When validating, check that there is no reservation at that time
        booking_list = cleaned_data['room'].booking_set.filter(
            is_validated=True,
            start_time__lt=end_time,
            end_time__gt=start_time,
            ).exclude(pk=self.instance.pk)

        if booking_list.exists():
            raise forms.ValidationError("There is already a booking at this time.")

        # Check that end time is after start time
        if start_time and end_time and start_time > end_time:
            raise forms.ValidationError("booking must end after it begins.")

        # Check that start time is not in the past
        now = timezone.now()
        if start_time and now > start_time:
            raise forms.ValidationError("You can't make a booking in the past.")

        return cleaned_data

booking/views.py
from django.shortcuts import render,redirect
from django.forms.fields import DateTimeField
from .forms import BookingForm
from .models import Booking
from django.contrib import messages

# Create your views here.


# @login_required(login_url="/login/")
def booking(request):
    if request.method == "POST":
        form = BookingForm(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            user = request.user
            instance.user = user
            instance.save()
            # form.save()
            messages.success(request,'Leave the request sent, wait for the response from the HRD',extra_tags = 'alert alert-success alert-dismissible show')
            return redirect('book')
    else:
        form = BookingForm()
    return render(request,'book.html',{"form":form})

booking/templates/book.html
{% extends "head.html" %}

{% load crispy_forms_tags %}


{% block profile %}
<section class="container-fluid">
    <section class="row">
        <section class="col col-sm-8 offset-sm-2">

            {% if  messages %}
                    {% for message in messages %}
                        <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                            {{ message }}
                            <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
            {% endif %}

        </section>
    </section>
    
<button class="btn btn-default" data-toggle="modal"  data-target=".bs-example-modal-lg">clich here to verify</button> </center>

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true"  id="onload">

    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">×</button>
        </div>
        <div class="modal-body">
                {% for bk in bk %}
                    <p>la salle sera dispo d'ici <strong>{{bk.end_time | timeuntil}}</strong></p>
            {% endfor %}
        </div>
        <div class="modal-footer">
        </div>
      </div>

    </div>
</div>

<div class="container bootstrap snippet">
    <div class="row">
  		<div class="col-sm-10" ><h3>Meeting Room</h3></div>
    </div>
    
    <div class="col-sm-8"><!--left col-->
    <br>
        <section class="col-lg-12 col-md-12 col-sm-12">
                <form  method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-success btn-lg btn-block">Reserve Meeting Room</button>
                </form>
            </section>
    </div><!--/col-9-->
</div> 
 <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />


    <script>
        $('#id_start_time').datetimepicker({
            footer: true,
            modal: true,
            format: 'dd-mm-yyyy hh:ii'
        });

        $('#id_end_time').datetimepicker({
            footer: true,
            modal: true,
            format: 'dd-mm-yyyy hh:ii'
        });
    </script>

{% endblock %}