EMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('access.urls')),
    path('hrd/', include('employee.urls')),
    path('',include('leave.urls')),
    path('reservation/',include('booking.urls')),
    path("blog/", include('chat.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'SUDPAY ADMINISTRATION'

employee/urls.py
from django.urls import path
from . import views


urlpatterns = [
	path('hrd_index/', views.hrd_index, name='hrdindex'),
	path('user/', views.hrd_user, name='hrd_user'),
	path('employee/create/', views.hrd_emp_create, name='emp_create'),
	path('employee/details/<int:id>/', views.hrd_emp_details, name='hrd_emp_details'),
	path('employee/edit/<int:id>/', views.hrd_emp_edit, name='emp_edit'),
	path('leave/all/', views.hrd_leave_all, name='leave_all'),
	path('leave/details/<int:id>/', views.hrd_leave_details, name='hrd_leave_details'),
	path('leave/status/<int:id>/', views.hrd_leave_status, name='leave_status'),
	path('leave/response/all/', views.hrd_response_create, name='response_all'),
	path('leave/response/details/<int:id>/', views.hrd_response_details, name='details_response'),
	path("post/views/", views.hrd_postviews, name="hrd_post"),
    path("post/details/<int:id>/", views.hrd_postdetail, name="hrd_post_detail"),
]

employee/models.py
import datetime
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import ugettext as _
# from django.contrib.auth.models import User
from access.models import User
from leave.models import Leave
import secrets

# from leave.models import Leave



# Create your models here.






class Fliale(models.Model):
    '''
     Table des fliales
    '''
    name = models.CharField(max_length=125)
    description = models.TextField(max_length=250,null=True,blank=True)

    created = models.DateTimeField(verbose_name=_('Created'),auto_now_add=True)
    updated = models.DateTimeField(verbose_name=_('Updated'),auto_now=True)


    class Meta:
        verbose_name = _('Fliale')
        verbose_name_plural = _('Fliales')
        ordering = ['name','created']
    
    def __str__(self):
        return self.name




class Employee(models.Model):

    def my_secret():
        return secrets.token_urlsafe(8)[:8] 

 
    GENDER = (
    ('MALE','Male'),
    ('FEMALE','Female'),
    )


    TITLE = (
    ('MR','Mr'),
    ('MRS','Mrs'),
    ('MSS','Mss'),
    ('DR','Dr'),
    ('SIR','Sir'),
    ('MADAM','Madam'),
    )


    
    COMMUNES = (
    ('Dakar', 'Dakar'),('Guédiawaye','Guédiawaye'),('Pikine','Pikine'),('Bargny','Bargny'), ('Diamniadio','Diamniadio'), ('Rufisque','Rufisque'),
    ('Sébikhotane','Sébikhotane'), ('Bambey','Bambey'),('Diourbel','Diourbel'), ('Mbacké','Mbacké'), ('Diofior','Diofior'), ('Fatick','Fatick'),('Foundiougne','Foundiougne') ,
    ('Karang' ,'Karang') ,('Passy','Passy') ,('Sokone','Sokone'),('Soum','Soum'),('Gossas','Gossas'),('Birkelane','Birkelane'),('Kaffrine','Kaffrine'),('Nganda','Nganda'),
    ('Koungheul','Koungheul'),('Malem-Hodar','Malem-Hodar'),('Guinguinéo','Guinguinéo'),('Mboss','Mboss'),('Gandiaye','Gandiaye'),('Kahone','Kahone'),('Kaolack','Kaolack'),('Ndoffane','Ndoffane') ,
    ('Sibassor','Sibassor'),('Nioro_du_Rip','Nioro_du_Rip'),('keur_Madiabel','keur_Madiabel'),('Kédougou','Kédougou'),('Salemata','Salemata'),('Saraya','Saraya'), ('Kolda','Kolda'), ('Dabo','Dabo'), 
    ('Salikégné','Salikégné'),('Médina_Yoro_Foulah','Médina_Yoro_Foulah'), ('Pata','Pata'),('Vélingara','Vélingara'), ('Kounkané','Kounkané'), ('Diaobé_Kabendou','Diaobé_Kabendou'),
    ('Kébémer','Kébémer'), ('Guéoul','Guéoul'),('Dahra','Dahra'), ('Linguère','Linguère'),('Louga','Louga'), ('Ndiagne','Ndiagne'),('Niomré','Niomré'),('Dembakané','Dembakané'), ('Hamady_Hounaré','Hamady_Hounaré'), 
    ('Kanel','Kanel'), ('Semmé','Semmé'), ('Aouré','Aouré'),('Bokiladji','Bokiladji'), ('Sinthiou','Sinthiou'), ('Bamambé','Bamambé'),('Banadji','Banadji'), ('Waounde','Waounde'),('Matam','Matam'), ('Ourossogui','Ourossogui'), 
    ('Thilogne','Thilogne'), ('Agnam_Civol','Agnam_Civol'),('Bokidiawé','Bokidiawé'),('Ranérou','Ranérou'),('Dagana','Dagana'), ('Gaé','Gaé'),('Richard_Toll','Richard_Toll'),('Ross_Béthio','Ross_Béthio'), ('Rosso','Rosso'),('Aéré_Lao','Aéré_Lao') ,
    ('Bodé_Lao','Bodé_Lao'), ('Démette','Démette') ,('Galoya_Toucouleur','Galoya_Toucouleur'), ('Golléré','Golléré') ,('Guédé_Chantier','Guédé_Chantier'), ('Mboumba','Mboumba') , ('Niandane','Niandane'), ('Ndioum','Ndioum'), ('Pété','Pété') ,
    ('Podor','Podor') ,('Walaldé','Walaldé'), ('Saint_Louis','Saint_Louis'), ('Mpal','Mpal'),('Bounkiling','Bounkiling'),('Madina_Wandifa','Madina_Wandifa'),('Diattacounda','Diattacounda') , ('Goudomp','Goudomp'), ('Samine','Samine'), ('Tanaff','Tanaff'),
    ('Diannah_Malary','Diannah_Malary' ),('Marsassoum','Marsassoum'),('Sédhiou','Sédhiou'),('Bakel','Bakel'),('Diawara','Diawara') , ('Kidira','Kidira'),('Goudiry','Goudiry'), ('Kothiary','Kothiary'),('Koumpentoum','Koumpentoum'), ('Malem_Niani','Malem_Niani'),('Tambacounda','Tambacounda'),
    ('Joal_Fadiouth','Joal_Fadiouth'),  ('Mbour','Mbour'),('Ngaparou','Ngaparou') ,('Nguékhokh','Nguékhokh') ,('Popenguine_Ndayane','Popenguine_Ndayane'),('Saly_Portudal','Saly_Portudal'), ('Somone','Somone'),('Thiadiaye','Thiadiaye') ,('Ndiaganiao','Ndiaganiao'),
    ('Thiès','Thiès') ,('Kayar','Kayar') ,('Khombole','Khombole') ,('Pout','Pout'),('Mboro','Mboro') ,('Meckhe','Meckhe'), ('Tivaouane','Tivaouane'),('Bignona','Bignona'), ('Thionck_Essyl','Thionck_Essyl') , ('Diouloulou','Diouloulou'), ('Oussouye','Oussouye'),('Ziguinchor','Ziguinchor'),
    )



    # PERSONAL DATA
    user = models.OneToOneField(User,on_delete=models.CASCADE, related_name="employee" )
    title = models.CharField(_('Title'),max_length=10,default='MR',choices=TITLE,blank=True,null=True)
    image = models.FileField(_('Profile Image'),upload_to='profiles',default='default.png',blank=True,null=True,help_text='upload image size less than 2.0MB')#work on path username-date/image
    get_full_name = models.CharField(_('Fullname'),max_length=125,null=False,blank=False)
    sex = models.CharField(_('Gender'),max_length=8, default='MALE', choices=GENDER, blank=False)
    tel = PhoneNumberField(default='+221771239025', null = False, blank=False, verbose_name='Phone Number (Example +221771239025)', help_text= 'Enter number with Country Code Eg. +221771239025')
    birthday = models.DateField(_('Birthday'),blank=False,null=False)
    place_of_birth = models.CharField(_('Region'),help_text='what town of the country(senegal) are you from ?', max_length=20, default='Dakar', choices=COMMUNES, blank=False, null=True)
    address = models.CharField(_('Address'),help_text='address of current residence',max_length=125,null=True,blank=True)
    token = models.CharField(max_length=8, editable=False, default=my_secret)

    fliale =  models.ForeignKey(Fliale, verbose_name =_('Fliales'),on_delete=models.SET_NULL, null=True,default=None)
    startdate = models.DateField(_('Employement Date'),help_text='date of employement',blank=False,null=True)

    is_blocked = models.BooleanField(_('Is Blocked'),help_text='button to toggle employee block and unblock',default=False)
    is_deleted = models.BooleanField(_('Is Deleted'),help_text='button to toggle employee deleted and undelete',default=False)
 
    created = models.DateTimeField(verbose_name=_('Created'),auto_now_add=True,null=True)
    updated = models.DateTimeField(verbose_name=_('Updated'),auto_now=True,null=True)




   
    
    class Meta:
        verbose_name = _('Employee')
        verbose_name_plural = _('Employees')
        ordering = ['-created']



    def __str__(self):
        return self.get_full_name

    

    @property
    def get_age(self):
        current_year = datetime.date.today().year
        dateofbirth_year = self.birthday.year
        if dateofbirth_year:
            return current_year - dateofbirth_year
        return


class Response(models.Model):
    """docstring for Response"""
    leave = models.OneToOneField(Leave, on_delete=models.CASCADE)
    reson = models.TextField(max_length=250, help_text="reson for no validation or cancelled?")
    firstdate = models.DateField(blank=True, null=True)
    enddate = models.DateField(blank=True, null=True)
    created = models.DateField(auto_now_add=True)
    update = models.DateField(auto_now=True)

    def __str__(self):
        return '{}, {}'.format(self.leave.title, self.leave.user)

        


   

employee/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .models import Employee,Response
from access.models import User
from leave.models import Leave
from leave.forms import LeavehrdForm
from booking.models import Booking
from chat.models import Post
from chat.forms import PostForm, CommentForm
from . forms import EmployeeCreateForm,ResponseForm,UserForm
from django.contrib.auth.decorators import login_required




@login_required(login_url="/login/")
def hrd_index(request):
	if not (request.user.is_authenticated and request.user.is_admin and request.user.is_staff):
		return redirect('/login/')
	emp = Employee.objects.all()
	leave = Leave.objects.all()
	booking = Booking.objects.all()
	user = User.objects.all()
	# on_user = request.user
	# employee =on_user.employee
	template = "index.html"
	context={
		"emp":emp,
		"booking":booking,
		"leave":leave,
		"user":user,
		# "employee":employee
	}

	return render(request, template, context)


# --------------fonction CRUD pour la gestion des employees  --------------->

@login_required(login_url="/login/")
def hrd_emp_details(request, id):
	if not (request.user.is_authenticated and request.user.is_admin and request.user.is_staff):
		return redirect('/login/')
	empid = get_object_or_404(Employee, id=id)
	# delt = get_object_or_404(Employee, id=id)
	if request.method == "POST":
		empid.delete()
		messages.success(request,'Account Deleted Successfully !!!',extra_tags = 'alert alert-success alert-dismissible show')
		return redirect("hrdindex")
	template = "hrd_emp_details.html"
	context = {
		'empid':empid,
		# 'delt':delt,
		}
	return render(request, template, context)


@login_required(login_url="/login/")
def hrd_emp_create(request):
	if not (request.user.is_authenticated and request.user.is_admin and request.user.is_staff):
		return redirect('/login/')
	form = EmployeeCreateForm(request.POST or None)
	if request.method == 'POST':
		if form.is_valid():
			instance = form.save(commit = False)
			instance.save()
			return  redirect('hrdindex')
		else:
			messages.error(request,'Trying to create dublicate employees with a single user account ',extra_tags = 'alert alert-warning alert-dismissible show')
			return redirect('emp_create')

	template = 'hrd_employee_create.html'
	context = {
		'form':form,
	}
	return render(request, template ,context)


@login_required(login_url="/login/")
def hrd_emp_edit(request, id):
	if not (request.user.is_authenticated and request.user.is_admin and request.user.is_staff):
		return redirect('/login/')
	instance = get_object_or_404(Employee, id=id)
	form = EmployeeCreateForm(request.POST or None,instance = instance)
	if request.method == "POST":
		if form.is_valid():
			instance = form.save(commit=False)
			instance.save()
			messages.success(request,'Account Updated Successfully !!!',extra_tags = 'alert alert-success alert-dismissible show')
			return redirect("hrdindex")
		else:
			messages.error(request,'Error Updating account',extra_tags = 'alert alert-warning alert-dismissible show')
			return HttpResponse("Form data not valid")
	template = "hrd_emp_edit.html"
	context = {
		'instance':instance,
		'form':form,
	}
	return render(request, template,context)



# --------------fonction CRUD pour la gestion de congee   --------------->
@login_required(login_url="/login/")
def hrd_leave_all(request):
	if not (request.user.is_authenticated and request.user.is_admin and request.user.is_staff):
		return redirect('/login/')
	leave_all = Leave.objects.all()
	template = "hrd_leave_all.html"
	context = {"leave_all":leave_all}
	return render(request, template, context)


@login_required(login_url="/login/")
def hrd_leave_details(request, id):
	if not (request.user.is_authenticated and request.user.is_admin and request.user.is_staff):
		return redirect('/login/')
	leaveid = get_object_or_404(Leave, id=id)
	if request.method == "POST":
		leaveid.delete()
		messages.success(request,'Leave Deleted Successfully !!!',extra_tags = 'alert alert-success alert-dismissible show')
		return redirect("hrdindex")
	template = "hrd_leave_details.html"
	context = {
		'leaveid':leaveid,
		}
	return render(request, template, context)


@login_required(login_url="/login/")
def hrd_leave_status(request, id):
	if not (request.user.is_authenticated and request.user.is_admin and request.user.is_staff):
		return redirect("/login/")
	instance = get_object_or_404(Leave, id=id)
	form = LeavehrdForm(request.POST or None, instance=instance)
	if request.method=="POST":
		if form.is_valid():
			instance=form.save(commit=False)
			instance.save()
			return redirect("leave_all")
		else:
			pass
	template = "hrd_leave_status.html"
	context = {
		"instance":instance, 
		"form":form,
		}
	return render(request, template, context)

# def hrd_status_all(request):
# 	response = Response.objects.all()
# 	template = "hrd_status_all.html"
# 	context = {
# 		"response":response,
# 	}
# 	return render(request, template, context)


@login_required(login_url="/login/")
def hrd_response_create(request):
	if not (request.user.is_authenticated and request.user.is_admin and request.user.is_staff):
		return redirect('/login/')
	form = ResponseForm(request.POST or None)
	response = Response.objects.all()
	leave = Leave.objects.all()
	if request.method == 'POST':
		if form.is_valid():
			instance = form.save(commit = False)
			instance.save()
			return  redirect('response_all')
		else:
			messages.error(request,'Trying to create dublicate employees with a single user account ',extra_tags = 'alert alert-warning alert-dismissible show')
			return redirect('employeecreate')

	template = 'hrd_response_create.html'
	context = {
		'form':form,
		"response":response,
		'leave':leave,
	}
	return render(request, template ,context)


@login_required(login_url="/login/")
def hrd_response_details(request, id):
	if not (request.user.is_authenticated and request.user.is_admin and request.user.is_staff):
		return redirect('/login/')
	responseid = get_object_or_404(Response, id=id)
	template = "hrd_response_details.html"
	context = {
		"responseid":responseid,
	}
	return render(request, template, context)


# <----------------------------forum-------------------------->

@login_required(login_url="/login/")
def hrd_postviews(request):
    chat = Post.objects.all().order_by('-created_on')
    paginator = Paginator(chat, 2) #show 10 employee lists per page

    page = request.GET.get('page')
    chat = paginator.get_page(page)
    if request.method == 'POST':
        posted = PostForm(request.POST)
        if posted.is_valid():
            instance = posted.save(commit=False)
            user = request.user
            instance.user = user
            instance.save()
            messages.success(request,'publication successfully sent',extra_tags = 'alert alert-success alert-dismissible show')
            return redirect('postcreate')
        messages.error(request,'failed to send publication',extra_tags = 'alert alert-warning alert-dismissible show')
    else:
        posted = PostForm()
    return render(request, "hrd_post_views.html" ,{'chat':chat,'posted':posted})


@login_required(login_url="/login/")
def hrd_postdetail(request, id):
    obj = get_object_or_404(Post, id=id)
    com = obj.comments.all()
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            #datas = form.cleaned_data
            #content = datas["body"]
            new_comment = comment_form.save(commit=False)
            
            new_comment.post = obj
            user = request.user
            new_comment.user = user
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, "hrd_post_detail.html",{'obj':obj,'com':com,'comment_form':comment_form})


# <---------------user------------------->
@login_required(login_url="/login/")
def hrd_user(request):
	if not (request.user.is_authenticated and request.user.is_admin and request.user.is_staff):
		return redirect('/login/')
	user = User.objects.all()
	form = UserForm(request.POST or None)
	if request.method == 'POST':
		if form.is_valid():
			instance = form.save(commit = False)
			instance.save()
			messages.success(request,'User added successfully',extra_tags = 'alert alert-success alert-dismissible show')
			return  redirect('hrd_user')
		else:
			messages.error(request,'Please check your credentials, Sorry no registration!! :-) ',extra_tags = 'alert alert-warning alert-dismissible show')
			return redirect('hrd_user')
	template = "hrd_user.html"
	context={

		"user":user,
		"form":form,
	}

	return render(request, template, context)

employee/templates/hrd_emp_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


 {% block profile %}
        <section class="content">
            <section class="container-fluid">
                    <section class="row">
                        <section class="col col-sm-8 offset-sm-2">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>
                    <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
            </section> <!-- /container --> 
        </section>
 {% endblock %}

employee/templates/hrd_emp_edit.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

        <!--CONTENTS-->
 {% block profile %}
        <section class="content">
            <section class="container-fluid">
              <section class="row">
                <section class="col col-lg-12">
                  <span><a href="{{request.META.HTTP_REFERER|escape}}" style="color:#565656;">Back</a></span>
                </section>
              </section>
                      <section class="row">
                        <section class="col col-lg-12 col-md-12  col-sm-12">
                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>

                    <section class="col-lg-8 col-md-8 col-sm-8">
                      <form  method="POST">
                          {% csrf_token %}
                          {{ form | crispy }}
                          <button type="submit" class="btn btn-success">Update</button>
                      </form>
                    </section>
                  
                
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}

{% endblock %}
</script>

employee/templates/hrd_employee_create.html
{% extends 'base.html' %}
{% loaad 'static'% }
{% load crispy_forms_tags %}


 {% block profile %}
        <section class="content">
            <section class="container-fluid">
                    <section class="row">
                        <section class="col col-sm-8 offset-sm-2">

                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>
           
                <section class="form-wrapper">

                    <section class="row">
                        <section class="col-lg-12 col-md-12 col-sm-12">
                            <h3 class="title-h3">Add Employee</h3>
                        </section>
                    </section>

                    <section class="row">
                        <section class="col-lg-8 col-md-12 col-sm-12">
                            <form action="" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{form | crispy }}
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                            </form>
                        </section>
                    </section>

                </section>
                <script type="text/javascript">
                    $(function () {
                        $('#id_birthday').datetimepicker();
                    });
                </script>
            </section> <!-- /container --> 
        </section>
 {% endblock %}

employee/templates/hrd_leave_all.html
{% extends 'base.html' %}

{% block profile %}
	<!-- DataTales Example -->
<br>
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>User</th>
                      <th>Title</th>
                      <th>Type</th>
                      <th>Start</th>
                      <th>End</th>
                      <th>Status</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  
                  <tbody>
                  {% for l in leave_all %}
                    <tr>
                        <td>{{ l.user }}</td>
                        <td>{{ l.title }}</td>
                        <td>{{l.leavetype}}</td>
                        <td>{{ l.startdate }}</td>
                        <td>{{ l.enddate }}</td>
                        {% if l.is_cancelled %}
                        <td style="color:red;">Refused</td>                      
                            {% elif l.is_approved %}
                            <td style="color: green;">Accepted</td>
                            {% else %}
                            <td style="color: blue">{{l.status}}</td>
                            {% endif %}
                         <td> 
                            <a href="{% url 'hrd_leave_details' l.id %}"><i class="fa fa-eye" aria-hidden="true"></i>
                            </a>
                            <a href="{% url 'leave_status' l.id %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
            </section> <!-- /container --> 
        </section>

{%endblock%}

employee/templates/hrd_leave_details.html
{% extends "base.html" %}

{% block profile %}

<style type="text/css">
   
</style>

<!------ Include the above in your HEAD tag ---------->

<section class="row">
    <section class="col col-sm-8 offset-sm-2">

        {% if  messages %}
                {% for message in messages %}
                 <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                     {{ message }}
                     <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                     </button>
                 </div>
                {% endfor %}
        {% endif %}

    </section>
</section>


<div class="row col-md-8 ">
    <div class="panel panel-default">
        <div class="panel-heading"><h4><strong> Object</strong> : {{leaveid.title}}</h4></div>
        <div class="panel-body"><h6><strong> Reason</strong> : {{leaveid.leavetype}}</h6></div>
        <div class="panel-body"><h6><strong>Start & End Date</strong> : from {{leaveid.startdate}}  to {{leaveid.enddate}}</h6></div>
        {% if leaveid.is_approved  %}
        <div class="panel-body"><h6> <strong>Status</strong> :  <strong style="color:green;"> Your leaveid is approved</strong></td>
        {% elif leaveid.is_cancelled %}
        <div class="panel-body"> <h6><strong> Status</strong> :  <strong style="color:red;"> Sorry! leaveid Cancelled</strong></h6></div>
        {% else %}
        <div class="panel-body"> <h6><strong> Status</strong> :  <strong style="color:blue;"> {{leaveid.status}}</strong></h6></div>
        {% endif %}
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete {{empid.get_full_name}}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
       <form action="." method="POST">
        {% csrf_token %}
        <div class="modal-body">
                Are you sure to dele "{{empid.get_full_name}}"???
        </div>
        <div class="modal-footer">
            
            <input type="submit" class="btn btn-danger"  value="Yes">
            <a type="button" href="./" class="btn btn-primary">Cancell</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

employee/templates/hrd_leave_status.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

        <!--CONTENTS-->
 {% block profile %}
        <section class="content">
            <section class="container-fluid">
              <section class="row">
                <section class="col col-lg-12">
                  <span><a href="{{request.META.HTTP_REFERER|escape}}" style="color:#565656;">Back</a></span>
                </section>
              </section>
                      <section class="row">
                        <section class="col col-lg-12 col-md-12  col-sm-12">
                            {% if  messages %}
                                    {% for message in messages %}
                                     <div {% if message.tags %} class="{{ message.tags}}"{% endif %}>
                                         {{ message }}
                                         <button type="button" class="close" id = "override-start"data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                                         </button>
                                     </div>
                                    {% endfor %}
                            {% endif %}

                        </section>
                    </section>

                    <section class="col-lg-8 col-md-8 col-sm-8">
                      <form  method="POST">
                          {% csrf_token %}
                          {{ form | crispy }}
                          <button type="submit" class="btn btn-success">Save</button>
                      </form>
                    </section>
                  
                
 {% endblock %}

<script type="text/javascript">
{% block extrajs%}

{% endblock %}
</script>